# Setup
title:               Hamza El Rhaffouli
tagline:             'Blog'
description:         'A blog to keep track of my self-learning adventures and side projects.
<br /> By <a href="https://twitter.com/SVallano" target="_blank">@SNeturo</a>.'
url:                 https://elrhaff.github.io/
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Hamza El Rhaffouli 
  url:               github.com/elrhaff
 # email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
# google_analytics_id: